# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10ab45576d72e2c38bd42a80c40a2bbce77d5d6227c51fa0216de751bbe1bb23501ce221b6cdba3c19d985f8f9c021fffd4bd6d27bf57722351fe2e3a21ce509

test:
  secret_key_base: cdd1a1ad626d539d99e99d5c5b5c1a4cf252d78ad338f1e0a4a740dbada762c331f94eeb6de41d0486850cb14cc8ced453d384c9bdf307f3e549c3b9d2ca8f66

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
